

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Nunito} from 'next/font/google'
import Navbar from "./components/navbar/Navbar";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
import { Suspense } from "react";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const font=Nunito({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "StaySphere",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo1.svg",
      href: "/images/logo1.svg",
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser=await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider/>
        <Suspense>
        <Navbar currentUser={currentUser}/>
        <SearchModal/>
        <RentModal/>
        <LoginModal/>
        <RegisterModal/>
        </Suspense>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  );
}
